/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cars2;


public class App 
{
    public static void main(String[] args) 
    {
        try 
        {
            mainSystem m = new mainSystem(); 
            Double[] toSort = {54.0, 703.0, 612.0, 84.0, 343.0, 480.0};
            Double[] sortedList = m.sortListRadix(toSort);
                  
        } catch (Exception e) 
        {
             // TODO: handle exception
            System.out.println(e);
        }
        System.out.println(new App().getGreeting());
    }

    /**
     * @return
     */
    public String getGreeting() 
    {
        return "Hello World!";
    }
}
