/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cars2;

public class App 
{
    public static void main(String[] args) 
    {
        try 
        {
            mainSystem m = new mainSystem(); 
                  
        } catch (Exception e) 
        {
             // TODO: handle exception
            System.out.println(e);
        }
        System.out.println(new App().getGreeting());
    }

    /**
     * @return
     */
    public String getGreeting() 
    {
        return "Hello World!";
    }
}
