/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cars2;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.LinkedList;

class AppTest {
    @Test void appStats() {
        try {
            mainSystem m = new mainSystem();
            assertNotNull(m);
            LinkedList<Double> data  = new LinkedList<Double>();
            data.add(1.0);
            data.add(2.0);
            data.add(2.0);
            data.add(3.0);
            data.add(4.0);
            data.add(5.0); 
            LinkedList<Double> dataX  = new LinkedList<Double>();
            dataX.add(1.4);
            dataX.add(6.7);
            dataX.add(3.8);
            dataX.add(9.5);
            dataX.add(11.2);
            dataX.add(13.5);
            dataX.add(17.9);
            LinkedList<Double> dataY  = new LinkedList<Double>();
            dataY.add(3.6);
            dataY.add(7.4);
            dataY.add(8.9);
            dataY.add(10.8);
            dataY.add(13.6);
            dataY.add(14.2);
            dataY.add(18.1);
            double mean = m.mean(data);
            assertEquals(2.8333333333333335, mean);
            double sd = m.standardDeviation(data);
            assertEquals(1.4719601443879744, sd);
            double r = m.aspectFaultCorrelation(dataX, dataY);
            assertEquals(0.9633050244441514, r);
            double skew = m.skew(data);
            assertEquals(0.4180715202995426, skew);
            String equation = m.regressionEquation(dataX, dataY);
            assertEquals("y = 0.8159870141316804x + 3.4824044422246354", equation);
            double mode = m.mode(dataY);
            assertEquals(-1.0, mode);
        } catch (Exception e) {
            // TODO Auto-generated catch block
            // e.printStackTrace();
            fail("failed to fetch mainSystem", e);
        }
    }
}
