/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cars2;


public class Library 
{
    public Library() {}

    public boolean someLibraryMethod() 
    {
        System.out.println("I can call the library from app");
        return true;
    }
}
