/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cars2;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.ArrayList;
import java.util.LinkedList;

class LibraryTest {
    @Test void practicalFunctions()
    {
        try {
            mainSystem m = new mainSystem();
            Vehicle mostFaults = m.mostFaults();
            ArrayList<Vehicle> vehTypeOfFault = m.vehiclesWithTypeOfFault("Software");
            ArrayList<Vehicle> vehActiveFaults = m.vehiclesWithActiveFaults();
            Fault mostCommonFault = m.mostCommonFault();
            Fault rarestFault = m.rarestFault();
            TimeWindow twTest = new TimeWindow("1970-01-01T00:00:00", "2023-02-03T23:59:59");
            double faultDensity = m.faultDensity(twTest);
            ArrayList<Fault> aroundFault = m.aroundFault(mostFaults, mostFaults.getFaultHistory().get(0), twTest, false);
            LinkedList<Double> vehicleYOMs = m.createDataList(m.getVehicleCollection(), "yearOfManufacture", 8, false);
        } catch (Exception e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
    }

    @Test void appStats() {
        try {
            mainSystem m = new mainSystem();
            assertNotNull(m);
            LinkedList<Double> data  = new LinkedList<Double>();
            data.add(1.0);
            data.add(2.0);
            data.add(2.0);
            data.add(3.0);
            data.add(4.0);
            data.add(5.0); 
            LinkedList<Double> dataX  = new LinkedList<Double>();
            dataX.add(1.4);
            dataX.add(6.7);
            dataX.add(3.8);
            dataX.add(9.5);
            dataX.add(11.2);
            dataX.add(13.5);
            dataX.add(17.9);
            LinkedList<Double> dataY  = new LinkedList<Double>();
            dataY.add(3.6);
            dataY.add(7.4);
            dataY.add(8.9);
            dataY.add(10.8);
            dataY.add(13.6);
            dataY.add(14.2);
            dataY.add(18.1);
            double mean = m.mean(data);
            assertEquals(2.8333333333333335, mean);
            double sd = m.standardDeviation(data);
            assertEquals(1.4719601443879744, sd);
            double r = m.aspectFaultCorrelation(dataX, dataY);
            assertEquals(0.9633050244441514, r);
            // LinkedList<Double> vehiclesYOMs = m.createDataList(m.getVehicleCollection(), "yearOfManufacture", 8, true);
            double skew = m.skew(data);
            assertEquals(0.4180715202995426, skew);
            String equation = m.regressionEquation(dataX, dataY);
            assertEquals("y = 0.8159870141316804x + 3.4824044422246354", equation);
            double mode = m.mode(dataY);
            assertEquals(-1.0, mode);
            Double[] toSort = {54.0, 703.0, 612.0, 84.0, 343.0, 480.0};
            Double[] sortedList = m.sortListMerge(toSort);
            Double[] expectedList = {54.0, 84.0, 343.0, 480.0, 612.0, 703.0}; 
            assertArrayEquals(sortedList, expectedList, "They are not equal");
        } catch (Exception e) {
            // TODO Auto-generated catch block
            // e.printStackTrace();
            fail("failed to fetch mainSystem", e);
        }
    }

    @Test void jsonSubTypes() 
    {
        try {
            mainSystem m = new mainSystem();
            Truck truck = new Truck("Truck", "RTERWERREE", "factory1", 1903, "ModelS", new ArrayList<String>(), "", false, 9.887766, 3.27867);
            SUV suv = new SUV("SUV", "RTERWERREF", "factory1", 1903, "ModelS", new ArrayList<String>(),  "", false, 7, 5);
            ArrayList<Vehicle> vList = new ArrayList<Vehicle>();
            vList.add(truck);
            vList.add(suv);
            m.addObject(vList, "TestVehicleArchive", Vehicle.class);
            Mechanical mech = new Mechanical("Mechanical", "YRHEIFYEFGFH", "Wheel", "1986-08-20T07:09:14", "1988-06-18T09:09:14", new ArrayList<String>(), false, "Wheel", 2, "Shock Loading");
            Electrical elect = new Electrical("Electrical", "EYERUEYRGWHRB", "Camera", "1987-07-22T07:10:20", "1999-08-10T09:13:20", new ArrayList<String>(), false, 3, 2, "ORTITRIE");
            ArrayList<Fault> fList = new ArrayList<Fault>();
            fList.add(mech);
            fList.add(elect);
            m.addObject(fList, "TestFaultArchive", Fault.class);
        } catch (Exception e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
    }
}
